#!/bin/sh

prog_spec=$0

# source the debian base ver
prog_deb=`echo $prog_spec | sed 's/-u$//'`-d
. $prog_deb

# Ubuntu-lize
sed -i "1s/ unstable;/ `lsb_release -cs`;/" debian/changelog
sed -i '$s/^.*$/\tdh $@/' debian/rules
sed -i '/^Build-Depends: /s/, dh-systemd//; /Standards-Version:/s/3.9.6/3.9.5/' debian/control
echo done.
